name: Setup Python Environment
description: Checkout code, set up Python, and install dependencies.
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install poetry
        poetry install --with dev

inputs:
  python-version:
    description: 'The Python version to use'
    required: true
