name: Run Tests and Publish on Release

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  # Pytest job
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run pytest
        run: |
          poetry run pytest

  # Pylint job
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run pylint
        run: |
          poetry run pylint $(git ls-files '*.py')

  # Pyright job
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run pyright
        run: |
          poetry run pyright

  # Publish job (only runs on release)
  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [pytest, pylint, pyright]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Build the package
        run: |
          poetry build

      - name: Publish to PyPI
        env:
          PUBLISHING_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username __token__ --password $PUBLISHING_TOKEN

  # Generate and push documentation
  generate-docs:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [pytest, pylint, pyright]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Sphinx and other dependencies
        run: |
          poetry install --with docs

      - name: Build Sphinx documentation
        run: |
          poetry run sphinx-build -b html docs/ _build/html

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          git rm -rf .
          cp -r _build/html/* .
          git add .
          git commit -m "Update documentation for ${{ github.sha }}"
          git push origin gh-pages
