name: Run Pytest and Pylint
description: Runs the pytest and pylint testing suites against the current project state.

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: <owner>/<repo>/.github/actions/setup-python@main
      with:
        python-version: '3.8'

    - name: Run pytest
      run: |
        poetry run pytest

  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: <owner>/<repo>/.github/actions/setup-python@main
      with:
        python-version: '3.8'

    - name: Run pylint
      run: |
        poetry run pylint --max-line-length=150 $(git ls-files '*.py')
